# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VentanaPrincipal.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_IngresoProcesos(object):
    def setupUi(self, IngresoProcesos):
        IngresoProcesos.setObjectName("IngresoProcesos")
        IngresoProcesos.resize(311, 324)
        self.centralwidget = QtWidgets.QWidget(IngresoProcesos)
        self.centralwidget.setObjectName("centralwidget")
        self.Titulo = QtWidgets.QLabel(self.centralwidget)
        self.Titulo.setGeometry(QtCore.QRect(50, 20, 191, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Titulo.setFont(font)
        self.Titulo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.Titulo.setWordWrap(True)
        self.Titulo.setObjectName("Titulo")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 100, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.Nprocesos = QtWidgets.QSpinBox(self.centralwidget)
        self.Nprocesos.setGeometry(QtCore.QRect(120, 170, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.Nprocesos.setFont(font)
        self.Nprocesos.setAlignment(QtCore.Qt.AlignCenter)
        self.Nprocesos.setReadOnly(True)
        self.Nprocesos.setObjectName("Nprocesos")
        self.saveProcessBtn = QtWidgets.QPushButton(self.centralwidget)
        self.saveProcessBtn.setGeometry(QtCore.QRect(90, 230, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.saveProcessBtn.setFont(font)
        self.saveProcessBtn.setObjectName("saveProcessBtn")
        IngresoProcesos.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(IngresoProcesos)
        self.statusbar.setObjectName("statusbar")
        IngresoProcesos.setStatusBar(self.statusbar)

        self.retranslateUi(IngresoProcesos)
        QtCore.QMetaObject.connectSlotsByName(IngresoProcesos)

    def retranslateUi(self, IngresoProcesos):
        _translate = QtCore.QCoreApplication.translate
        IngresoProcesos.setWindowTitle(_translate("IngresoProcesos", "Procesamiento por Lotes"))
        self.Titulo.setText(_translate("IngresoProcesos", "Captura de Procesos"))
        self.label.setText(_translate("IngresoProcesos", "Dame el numero de procesos a introducir:"))
        self.saveProcessBtn.setText(_translate("IngresoProcesos", "Confirmar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    IngresoProcesos = QtWidgets.QMainWindow()
    ui = Ui_IngresoProcesos()
    ui.setupUi(IngresoProcesos)
    IngresoProcesos.show()
    sys.exit(app.exec_())
